# Copyright (c) 2025, TheSkyC
# SPDX-License-Identifier: Apache-2.0

import os
from pathlib import Path
import re


def generate_i18n_function():
    # 自动定位项目根目录
    root_path = Path(__file__).parent.parent
    web_src_path = root_path / "web_src"

    # 1. 定义匹配正则和排除目录
    pattern = re.compile(r"(?<![\w.])(?:\$t|t)\(\s*(['\"])((?:[^\\]|\\.)*?)\1\s*\)")
    EXCLUDE_DIRS = {"node_modules", "dist", ".git", ".idea", ".vscode"}

    unique_keys = set()
    extensions = {".vue", ".js"}

    if not web_src_path.exists():
        print(f"❌ 错误: 找不到目录 {web_src_path}")
        return

    print(f"🔍 正在扫描目录: {web_src_path}")

    for root, dirs, files in os.walk(web_src_path):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for file in files:
            file_path = Path(root) / file
            if file_path.suffix in extensions:
                try:
                    with open(file_path, encoding="utf-8") as f:
                        content = f.read()
                        matches = pattern.findall(content)
                        for _, text in matches:
                            clean_text = text.replace("\\'", "'").replace('\\"', '"')
                            unique_keys.add(clean_text)
                except Exception as e:
                    print(f"⚠️ 读取失败 {file_path}: {e}")

    sorted_keys = sorted(unique_keys)

    # 2. 准备目标文件
    server_file = root_path / "src" / "lexisync" / "services" / "web_server_service.py"
    if not server_file.exists():
        print(f"❌ 错误: 找不到目标文件 {server_file}")
        return

    # 统一换行符
    raw_content = server_file.read_text(encoding="utf-8")
    content = "\n".join(raw_content.splitlines())

    # 3. 自动检测原有缩进
    indent_match = re.search(r"^([ \t]*)@app\.get\(\"/api/v1/i18n\"\)", content, re.MULTILINE)
    current_indent = indent_match.group(1) if indent_match else "        "

    # 4. 生成代码块（内部相对缩进）
    base_lines = [
        '@app.get("/api/v1/i18n")',
        "async def get_i18n(user: dict = Depends(self._verify_session)):",
        "    # -- i18n_start (Auto-generated by tools/extract_i18n.py) --",
        "    keys = [",
    ]
    for key in sorted_keys:
        safe_key = key.replace('"', '\\"')
        base_lines.append(f'        "{safe_key}",')
    base_lines.append("    ]")
    base_lines.append("    # -- i18n_end --")
    base_lines.append("    return {k: _(k) for k in keys}")

    # 5. 组装最终代码
    new_function_code = "\n".join([current_indent + line for line in base_lines])

    # 6. 执行替换
    replacement_pattern = re.compile(
        r"^[ \t]*@app\.get\(\"/api/v1/i18n\"\)\n\s*async def get_i18n.*?return \{k: _\(k\) for k in keys\}",
        re.DOTALL | re.MULTILINE,
    )

    if replacement_pattern.search(content):
        new_content = replacement_pattern.sub(new_function_code, content, count=1)

        with open(server_file, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_content)

        print(f"✅ 成功: 已完美对齐缩进并更新 {len(sorted_keys)} 个词条。")
    else:
        print("⚠️ 错误: 无法匹配到函数区域。请检查代码中是否已有该函数。")


if __name__ == "__main__":
    generate_i18n_function()
