import os
from pathlib import Path
import re


def generate_i18n_function():
    root_path = Path(__file__).parent.parent
    web_src_path = root_path / "web_src"

    # 1. 增强版正则
    pattern = re.compile(r"(?<![\w.])(?:\$t|t)\(\s*(['\"])((?:[^\\]|\\.)*?)\1", re.DOTALL)

    EXCLUDE_DIRS = {"node_modules", "dist", ".git", ".idea", ".vscode", "assets"}
    extensions = {".vue", ".js", ".ts"}

    PUBLIC_FILES = {"AuthDialog.vue", "auth.js"}

    all_keys = set()
    public_keys = set()

    if not web_src_path.exists():
        print(f"❌ 错误: 找不到目录 {web_src_path}")
        return

    print("🔍 正在智能扫描 Web 源码...")

    for root, dirs, files in os.walk(web_src_path):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for file in files:
            file_path = Path(root) / file
            if file_path.suffix in extensions:
                is_public_file = file in PUBLIC_FILES
                try:
                    with open(file_path, encoding="utf-8-sig") as f:
                        content = f.read()
                        for match in pattern.finditer(content):
                            text = match.group(2)
                            clean_text = text.replace("\\'", "'").replace('\\"', '"')
                            if clean_text.strip():
                                all_keys.add(clean_text)
                                # 如果当前文件属于公开文件，则将其词条加入公开集合
                                if is_public_file:
                                    public_keys.add(clean_text)
                except Exception as e:
                    print(f"⚠️ 读取失败 {file_path}: {e}")

    sorted_all_keys = sorted(list(all_keys))
    sorted_public_keys = sorted(list(public_keys))

    # 2. 准备更新目标文件
    server_file = root_path / "src" / "lexisync" / "services" / "web_server_service.py"
    if not server_file.exists():
        print(f"❌ 错误: 找不到目标文件 {server_file}")
        return

    raw_content = server_file.read_text(encoding="utf-8")
    content = "\n".join(raw_content.splitlines())

    # 3. 自动检测缩进
    indent_match = re.search(r"^([ \t]*)@app\.get\(\"/api/v1/i18n\"\)", content, re.MULTILINE)
    current_indent = indent_match.group(1) if indent_match else "        "

    # 4. 生成代码块 (同时生成 public-i18n 和 i18n 两个路由)
    base_lines = [
        '@app.get("/api/v1/public-i18n")',
        "async def get_public_i18n():",
        "    # -- public_i18n_start (Auto-generated by tools/extract_i18n.py) --",
        "    public_keys = [",
    ]
    for key in sorted_public_keys:
        safe_key = key.replace("\\", "\\\\").replace('"', '\\"')
        base_lines.append(f'        "{safe_key}",')

    base_lines.extend(
        [
            "    ]",
            "    # -- public_i18n_end --",
            "    return {k: _(k) for k in public_keys}",
            "",
            '@app.get("/api/v1/i18n")',
            "async def get_i18n(user: dict = Depends(self._verify_session)):",
            "    # -- i18n_start (Auto-generated by tools/extract_i18n.py) --",
            "    keys = [",
        ]
    )

    for key in sorted_all_keys:
        safe_key = key.replace("\\", "\\\\").replace('"', '\\"')
        base_lines.append(f'        "{safe_key}",')

    base_lines.extend(["    ]", "    # -- i18n_end --", "    return {k: _(k) for k in keys}"])

    new_function_code = "\n".join([current_indent + line if line else "" for line in base_lines])

    # 5. 执行替换
    replacement_pattern = re.compile(
        r"(?:^[ \t]*@app\.get\(\"/api/v1/public-i18n\"\)\n\s*async def get_public_i18n.*?return\s+\{.*?\}\n+)?^[ \t]*@app\.get\(\"/api/v1/i18n\"\)\n\s*async def get_i18n.*?return\s+\{k:\s*_\(k\)\s*for\s+k\s+in\s+keys\}",
        re.DOTALL | re.MULTILINE,
    )

    if replacement_pattern.search(content):
        new_content = replacement_pattern.sub(new_function_code, content, count=1)
        with open(server_file, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_content)
        print(
            f"✅ 成功: 提取并更新了 {len(sorted_all_keys)} 个全量词条 (其中 {len(sorted_public_keys)} 个为公开词条)。"
        )
    else:
        print("⚠️ 匹配失败，请检查 web_server_service.py 中的函数格式。")


if __name__ == "__main__":
    generate_i18n_function()
